const KEY="velan_chit_fund_v1";
const seed={settings:{currency:"₹"},members:[],chits:[],bids:[]};
let db=load(), currentPage="dashboard", chitTab="Fixed", memberSearch="", bidSearch="";

function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function uid(p){return p+"_"+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function money(n){return (db.settings.currency||"₹")+" "+Number(n||0).toLocaleString("en-IN")}
function toast(s){const e=document.getElementById("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function member(id){return db.members.find(x=>x.id===id)}
function chit(id){return db.chits.find(x=>x.id===id)}
function initials(s){return String(s||"?").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}

document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;render()});

function render(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===currentPage));const m=document.getElementById("appMain");m.innerHTML=pages[currentPage]();bindPage()}

const pages={
dashboard(){const active=db.chits.filter(c=>c.status==="active").length, live=db.bids.filter(b=>b.status==="live").length, results=db.bids.filter(b=>b.status==="completed");return `<div class="page">
<div class="hero"><h2>Velan Chit Fund</h2><p>Simple, local & private chit management</p><div class="actions" style="margin-top:16px"><button class="btn btn-primary" onclick="currentPage='members';render()">+ Add Member</button><button class="btn btn-soft" onclick="currentPage='bid';render()">🔨 Start Auction</button></div></div>
<div class="stats"><div class="stat"><span class="muted">Members</span><b>${db.members.length}</b></div><div class="stat"><span class="muted">Fixed Chit</span><b>${db.chits.filter(c=>c.type==="Fixed").length}</b></div><div class="stat"><span class="muted">Devid Chit</span><b>${db.chits.filter(c=>c.type==="Devid").length}</b></div><div class="stat"><span class="muted">Active</span><b>${active}</b></div></div>
<div class="grid"><div class="card"><div class="section-head"><h3>Live Bid</h3><span class="badge badge-live">${live} LIVE</span></div>${live?db.bids.filter(b=>b.status==="live").map(b=>`<div class="row"><div><b>${esc(chit(b.chitId)?.name||"Chit")}</b><div class="row-sub">${esc(member(b.memberId)?.name||"No winner selected")}</div></div><button class="btn btn-primary" onclick="openBid('${b.id}')">Open</button></div>`).join(""):`<div class="empty">No live auctions right now.</div>`}</div>
<div class="card"><div class="section-head"><h3>Recent Results</h3><button class="btn btn-soft" onclick="currentPage='bid';render()">View all</button></div>${results.slice(-3).reverse().map(b=>`<div class="row result"><div><b>${esc(member(b.winnerId)?.name||"Winner")}</b><div class="row-sub">${esc(chit(b.chitId)?.name||"Chit")} • Round ${b.round}</div></div><b>${money(b.bidAmount)}</b></div>`).join("")||`<div class="empty">No results yet.</div>`}</div></div></div>`},
members(){const ms=db.members.filter(m=>m.name.toLowerCase().includes(memberSearch.toLowerCase())||String(m.phone||"").includes(memberSearch));return `<div class="page"><div class="section-head"><div><h2>Members</h2><div class="muted">${db.members.length} registered</div></div><button class="btn btn-primary" onclick="memberForm()">+ Add</button></div><input class="search" placeholder="Search name or phone" value="${esc(memberSearch)}" oninput="memberSearch=this.value;render()"><div class="list" style="margin-top:12px">${ms.map(m=>`<div class="row"><div class="row-main"><div class="avatar">${initials(m.name)}</div><div><div class="row-title">${esc(m.name)}</div><div class="row-sub">${esc(m.phone||"No phone")} • ${db.bids.filter(b=>b.winnerId===m.id).length} wins</div></div></div><div class="actions"><button class="btn btn-soft" onclick="memberForm('${m.id}')">Edit</button><button class="btn btn-danger" onclick="deleteMember('${m.id}')">Delete</button></div></div>`).join("")||`<div class="empty">No members found.</div>`}</div></div>`},
chits(){const cs=db.chits.filter(c=>c.type===chitTab);return `<div class="page"><div class="section-head"><div><h2>Chits</h2><div class="muted">Manage Fixed and Devid chit groups</div></div><button class="btn btn-primary" onclick="chitForm()">+ New Chit</button></div><div class="tabs"><button class="${chitTab==='Fixed'?'active':''}" onclick="chitTab='Fixed';render()">Fixed Chit</button><button class="${chitTab==='Devid'?'active':''}" onclick="chitTab='Devid';render()">Devid Chit</button></div><div class="list">${cs.map(c=>`<div class="row"><div class="row-main"><div class="avatar">₹</div><div><div class="row-title">${esc(c.name)} <span class="badge ${c.type==='Fixed'?'badge-fixed':'badge-devid'}">${c.type}</span></div><div class="row-sub">${c.members.length} members • ${money(c.amount)} • #${esc(c.code)}</div></div></div><div class="actions"><button class="btn btn-soft" onclick="chitForm('${c.id}')">Edit</button><button class="btn btn-primary" onclick="startAuction('${c.id}')">Bid</button></div></div>`).join("")||`<div class="empty">No ${chitTab} chits yet.</div>`}</div></div>`},
bid(){const available=db.chits;return `<div class="page"><div class="section-head"><div><h2>Auction</h2><div class="muted">Live bidding & round history</div></div></div><div class="grid">${available.map(c=>`<div class="card"><span class="badge ${c.type==='Fixed'?'badge-fixed':'badge-devid'}">${c.type}</span><h3>${esc(c.name)}</h3><p class="muted">${c.members.length} members • ${money(c.amount)}</p><button class="btn btn-primary" onclick="startAuction('${c.id}')">START</button></div>`).join("")||`<div class="empty">Create a chit first.</div>`}</div><div class="section-head"><h3>Round History</h3></div><input class="search" placeholder="Search winner / bid" value="${esc(bidSearch)}" oninput="bidSearch=this.value;render()"><div class="list" style="margin-top:12px">${db.bids.filter(b=>b.status==='completed').filter(b=>(member(b.winnerId)?.name||"").toLowerCase().includes(bidSearch.toLowerCase())||String(b.bidAmount).includes(bidSearch)).slice().reverse().map(b=>resultCard(b)).join("")||`<div class="empty">No completed bids.</div>`}</div></div>`},
settings(){return `<div class="page"><div class="section-head"><div><h2>Settings</h2><div class="muted">App preferences and backup</div></div></div><div class="card form"><div class="field"><label>Currency</label><select id="currency"><option ${db.settings.currency==='₹'?'selected':''}>₹</option><option ${db.settings.currency==='$'?'selected':''}>$</option><option ${db.settings.currency==='£'?'selected':''}>£</option></select></div><button class="btn btn-primary" onclick="saveSettings()">Save Settings</button></div><div class="card" style="margin-top:14px"><h3>Backup</h3><p class="muted">Export or restore all Members, Chits, Bids and Settings.</p><div class="actions"><button class="btn btn-soft" onclick="exportData()">Export JSON</button><label class="btn btn-soft">Import JSON<input hidden type="file" accept=".json" onchange="importData(event)"></label></div></div><div class="card" style="margin-top:14px"><h3>Danger Zone</h3><p class="muted">This permanently clears local data on this browser.</p><button class="btn btn-danger" onclick="clearData()">Clear All Data</button></div></div>`}
};

function resultCard(b){const c=chit(b.chitId),w=member(b.winnerId), take=Math.max(0,(c?.amount||0)-(b.bidAmount||0)), div=Math.round((c?.amount||0)/(c?.members?.length||1));return `<div class="row result"><div style="flex:1"><div class="row-title">🏆 ${esc(w?.name||"Winner")}</div><div class="row-sub">${esc(c?.name||"Chit")} • Round ${b.round} • ${new Date(b.createdAt).toLocaleDateString("en-GB")}</div><div style="margin-top:9px"><span class="muted">Auction</span> <b>${money(b.bidAmount)}</b> · <span class="muted">Take</span> <b>${money(take)}</b></div></div><button class="btn btn-soft" onclick="openBid('${b.id}')">View</button></div>`}

function memberForm(id){const m=id?member(id):{name:"",phone:"",address:""};showModal(id?"Edit Member":"Add Member",`<div class="form"><div class="field"><label>Name</label><input id="mName" value="${esc(m.name)}" required></div><div class="field"><label>Phone</label><input id="mPhone" value="${esc(m.phone||"")}"></div><div class="field"><label>Address</label><input id="mAddress" value="${esc(m.address||"")}"></div><button class="btn btn-primary" onclick="saveMember('${id||""}')">Save Member</button></div>`)}
function saveMember(id){const name=document.getElementById("mName").value.trim();if(!name)return alert("Enter member name.");if(id)Object.assign(member(id),{name,phone:mPhone.value.trim(),address:mAddress.value.trim()});else db.members.push({id:uid("mem"),name,phone:mPhone.value.trim(),address:mAddress.value.trim(),createdAt:Date.now()});save();closeModal();toast("Member saved");render()}
function deleteMember(id){if(!confirm("Delete this member? Existing bid history will remain."))return;db.members=db.members.filter(m=>m.id!==id);db.chits.forEach(c=>c.members=c.members.filter(x=>x!==id));save();render()}

function chitForm(id){const c=id?chit(id):{name:"",type:chitTab,amount:"",members:[],code:""};showModal(id?"Edit Chit":"New Chit",`<div class="form"><div class="field"><label>Chit Name</label><input id="cName" value="${esc(c.name)}"></div><div class="field"><label>Type</label><select id="cType"><option ${c.type==='Fixed'?'selected':''}>Fixed</option><option ${c.type==='Devid'?'selected':''}>Devid</option></select></div><div class="field"><label>Chit Amount</label><input id="cAmount" type="number" value="${c.amount||""}"></div><div class="field"><label>Chit No / Code</label><input id="cCode" value="${esc(c.code||"")}"></div><div class="field"><label>Assign Members</label><select id="cMembers" multiple size="5">${db.members.map(m=>`<option value="${m.id}" ${c.members.includes(m.id)?'selected':''}>${esc(m.name)}${m.phone?" • "+esc(m.phone):""}</option>`).join("")}</select></div><button class="btn btn-primary" onclick="saveChit('${id||""}')">Save Chit</button></div>`)}
function saveChit(id){const name=cName.value.trim(), amount=Number(cAmount.value);if(!name||!amount)return alert("Enter chit name and amount.");const members=[...cMembers.selectedOptions].map(o=>o.value);const data={name,type:cType.value,amount,code:cCode.value.trim()||"VC"+String(db.chits.length+1).padStart(4,"0"),members,status:"active"};if(id)Object.assign(chit(id),data);else db.chits.push({id:uid("chit"),...data});save();closeModal();toast("Chit saved");render()}

function startAuction(chitId){const c=chit(chitId);if(!c||!c.members.length)return alert("Assign at least one member to this chit.");const live=db.bids.find(b=>b.chitId===chitId&&b.status==="live");if(live)return openBid(live.id);const b={id:uid("bid"),chitId,round:db.bids.filter(x=>x.chitId===chitId).length+1,status:"live",bidAmount:0,winnerId:"",createdAt:Date.now()};db.bids.push(b);save();openBid(b.id)}
function openBid(id){const b=db.bids.find(x=>x.id===id);const c=chit(b.chitId);const isLive=b.status==="live";showModal(isLive?`${c.name} • Live bidding`:`${c.name} • Round ${b.round}`,isLive?liveBidForm(b,c):resultDetail(b,c))}
function liveBidForm(b,c){return `<div class="live-box"><span class="badge badge-live">● LIVE</span><h2>${esc(c.name)}</h2><p class="muted">${c.members.length} members • ${money(c.amount)} chit value</p><div class="big" id="liveBidValue">${money(b.bidAmount)}</div><div class="form" style="margin-top:14px"><div class="field"><label>Current Bid / Auction Amount</label><input id="bidAmount" type="number" min="0" value="${b.bidAmount||""}"></div><div class="field"><label>Winner</label><select id="winnerId"><option value="">Select winner</option>${c.members.map(id=>{const m=member(id);return `<option value="${id}" ${b.winnerId===id?'selected':''}>${esc(m?.name||"Unknown")}</option>`}).join("")}</select></div><button class="btn btn-danger" onclick="stopAuction('${b.id}')">STOP & CONFIRM</button></div></div><div class="section-head"><h3>Round ${b.round}</h3></div><p class="muted">Press START to begin bidding. Enter the final auction amount and winner, then confirm STOP.</p>`}
function stopAuction(id){const b=db.bids.find(x=>x.id===id),c=chit(b.chitId),amt=Number(document.getElementById("bidAmount").value),win=document.getElementById("winnerId").value;if(!amt||amt<=0||amt>c.amount)return alert("Bid must be greater than 0 and not exceed chit value.");if(!win)return alert("Select the winner.");if(!confirm("Stop bidding and save this result?"))return;b.bidAmount=amt;b.winnerId=win;b.status="completed";b.createdAt=Date.now();b.paymentStatus="Pending";b.payoutStatus="Paid";save();toast("Result saved");openBid(b.id);render()}
function resultDetail(b,c){const w=member(b.winnerId),take=c.amount-b.bidAmount,division=Math.round((c.amount-b.bidAmount)/(c.members.length||1)),payable=Math.max(0,division*2),prize=Math.max(0,take-payable);return `<div class="card"><span class="badge badge-live">RESULT SAVED</span><h2>🏆 ${esc(w?.name||"Winner")}</h2><p class="muted">${esc(c.name)} • Round ${b.round} • ${new Date(b.createdAt).toLocaleDateString("en-GB")}</p><div class="stats" style="margin-top:15px"><div class="stat"><span class="muted">Chit Amount</span><b>${money(c.amount)}</b></div><div class="stat"><span class="muted">Auction</span><b>${money(b.bidAmount)}</b></div><div class="stat"><span class="muted">Take Amount</span><b>${money(take)}</b></div><div class="stat"><span class="muted">Prize</span><b>${money(prize)}</b></div></div><div class="actions"><button class="btn btn-warning" onclick="togglePayment('${b.id}')">${b.paymentStatus==="Paid"?"Mark Pending":"Mark Paid"}</button><button class="btn btn-soft" onclick="deleteBid('${b.id}')">Delete</button></div></div><div class="card" style="margin-top:12px"><h3>Payment</h3><p class="muted">Installment status: <b>${b.paymentStatus}</b></p><button class="btn btn-soft" onclick="alert('Reminder feature is local-only. Add your preferred reminder action here.')">Remind Payment</button></div>`}
function togglePayment(id){const b=db.bids.find(x=>x.id===id);b.paymentStatus=b.paymentStatus==="Paid"?"Pending":"Paid";save();openBid(id);render()}
function deleteBid(id){if(!confirm("Delete this result?"))return;db.bids=db.bids.filter(b=>b.id!==id);save();closeModal();render()}
function saveSettings(){db.settings.currency=document.getElementById("currency").value;save();toast("Settings saved");render()}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="velan-chit-fund-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.members||!x.chits||!x.bids)throw 0;db=x;save();toast("Backup restored");render()}catch{alert("Invalid backup file.")}};r.readAsText(f)}
function clearData(){if(!confirm("Clear ALL local data? This cannot be undone."))return;db=structuredClone(seed);save();toast("Data cleared");render()}
function showModal(title,body){document.getElementById("modalTitle").textContent=title;document.getElementById("modalBody").innerHTML=body;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
function bindPage(){}
render();
